import type { CalendarEntry, VenueEvent } from "./types.js";

/**
 * The projection both record types serialize through, per `CONTEXT.md`
 * § CalendarEntry and ADR-0001.
 *
 * It is **a convenience, not a bottleneck** — it flattens away `vessel`, `hall`
 * and `berth`, and a serializer needing those (a future Excel export) reads the
 * domain types directly rather than widening this.
 *
 * Only the `VenueEvent` half exists here. The `PortCall` projection arrives with
 * the feed that renders it (`port-calls.ics`) rather than sitting unreachable
 * until then.
 */

/**
 * `description` is **generated by us, never scraped.**
 *
 * This is the whole of what survives the facts-only line: the scraped blurb was
 * ~8% populated on Suntec, absent from both cruise sources, and was the single
 * weakest thing we would have held legally. So the property carries **category
 * and attribution** — prose that is 100% populated and 0% scraped.
 *
 * It carries the category because `CATEGORIES` survives on only 1 of 3 major
 * clients (ADR-0001, #6). Standards conformance is not survival, and there is no
 * friendlier `X-` namespace to escape into, so the marker travels as prose or
 * not at all.
 */
const descriptionFor = (category: string, source: string): string =>
  `${category}.\nSource: ${source}.`;

export const projectVenueEvent = (record: VenueEvent): CalendarEntry => ({
  uid: record.uid,
  summary: record.name,
  start: record.start,
  end: record.end,
  // Venue plus hall: a hotelier heading there needs the room, not just the building.
  location: [record.venue, record.hall].filter((part) => part !== null).join(", "),
  description: descriptionFor("Venue event", record.source),
  source: record.source,
});
