import type { CalendarEntry, PortCall, VenueEvent } from "./types.js";

/**
 * The projection both record types serialize through, per `CONTEXT.md`
 * § CalendarEntry and ADR-0001.
 *
 * It is **a convenience, not a bottleneck** — it flattens away `vessel`, `hall`
 * and `berth`, and a serializer needing those (a future Excel export) reads the
 * domain types directly rather than widening this.
 */

/**
 * `description` is **generated by us, never scraped.**
 *
 * This is the whole of what survives the facts-only line: the scraped blurb was
 * ~8% populated on Suntec, absent from both cruise sources, and was the single
 * weakest thing we would have held legally. So the property carries **category
 * and attribution** — prose that is 100% populated and 0% scraped.
 *
 * It carries the category because `CATEGORIES` survives on only 1 of 3 major
 * clients (ADR-0001, #6). Standards conformance is not survival, and there is no
 * friendlier `X-` namespace to escape into, so the marker travels as prose or
 * not at all.
 */
const describe = (category: string, source: string, detail?: string): string =>
  [detail ? `${category} — ${detail}.` : `${category}.`, `Source: ${source}.`].join("\n");

export const projectVenueEvent = (record: VenueEvent): CalendarEntry => ({
  uid: record.uid,
  summary: record.name,
  start: record.start,
  end: record.end,
  // Venue plus hall: a hotelier heading there needs the room, not just the building.
  location: [record.venue, record.hall].filter((part) => part !== null).join(", "),
  description: describe("Venue event", record.source),
  source: record.source,
});

export const projectPortCall = (record: PortCall): CalendarEntry => ({
  uid: record.uid,
  // A port call has no name — this label is ours, and says so by construction.
  summary: `Cruise: ${record.vessel} at ${record.terminal}`,
  start: record.arrival,
  end: record.departure,
  // The terminal, **never the berth**. A pier number is not reader-facing;
  // it is demoted into the description below.
  location: record.terminal,
  description: describe(
    "Cruise port call",
    record.source,
    record.berth === null ? undefined : `berth ${record.berth}`,
  ),
  source: record.source,
});
